name: hd-tree-secp256k1
version: "0.0.0"
category: "Cryptography, Key Generation"
synopsis: Implementation of HD Trees for 256 bit elliptic curve keys
description: |
  Bip32 (https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)
  Bip39 (https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki)
  Bip43 (https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki)
  Bip44 (https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki)
license: MIT
author: "CaptJakk"
copyright: "Keagan (CaptJakk) McClelland"
maintainer: "keagan.mcclelland@gmail.com"

dependencies:
  - base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5
  - base16-bytestring
  - base58-bytestring
  - basement
  - bytestring
  - cereal
  - cryptonite
  - lens
  - memory
  - secp256k1-haskell
  - trifecta
  - either

library:
  source-dirs:
    - src
  exposed-modules:
    - Crypto.HDTree.Bip32
    - Crypto.HDTree.Bip32.ExtendedKeys
    - Crypto.HDTree.Address
  ghc-options:
    - -Wall
    - -fwarn-tabs
    - -fdefer-typed-holes

tests:
  spec:
    main: "Spec.hs"
    ghc-options: "-threaded -O0"
    source-dirs:
      - src
      - test

    dependencies:
      - hspec
      - QuickCheck
      - safe

github: CaptJakk/hd-tree-secp256k1